# LiveKit Ingress Configuration
# https://docs.livekit.io/realtime/egress-ingress/ingress/

api_key: devkey
api_secret: mCafIFJr80hhRBYVBKCUqgOLEiIpRFLj5RAfEaNjF8p
ws_url: ws://livekit:7880

redis:
  address: redis:6379

logging:
  level: info

rtmp_port: 1935
whip_port: 8080

cpu_cost:
  rtmp_cpu_cost: 2.0
  whip_cpu_cost: 2.0
