# LiveKit Server Configuration
# https://docs.livekit.io/realtime/self-hosting/deployment/

port: 7880
rtc:
  port_range_start: 50100
  port_range_end: 50200
  tcp_port: 7881
  use_external_ip: true

redis:
  address: redis:6379

keys:
  devkey: mCafIFJr80hhRBYVBKCUqgOLEiIpRFLj5RAfEaNjF8p
  APIwQJRKPH1GaLa: mCafIFJr80hhRBYVBKCUqgOLEiIpRFLj5RAfEaNjF8p

logging:
  level: info
  json: false

room:
  empty_timeout: 300
  max_participants: 100

turn:
  enabled: false
