# LiveKit SIP Configuration
# https://docs.livekit.io/sip/

api_key: devkey
api_secret: mCafIFJr80hhRBYVBKCUqgOLEiIpRFLj5RAfEaNjF8p
ws_url: ws://livekit:7880

logging:
  level: info

sip:
  signaling_port: 5060
  signaling_ip: 0.0.0.0
